name: CD
on:
  push:
    branches:
      - main
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        if: github.repository == 'JoinAI-Inc/AI_Service_Template'

        steps:
            - uses: actions/checkout@v4
            
